version: "3.3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  qrate-backend:
    image: somnath6646/qrate-backend
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
